name: gen
description: A command-line tool for multiple commands in Flutter.
publish_to: "none" # Prevents publishing to pub.dev
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# Update this section for command-line entry points
executables:
  gen: gen # This line now refers to the command directly, assuming bin/gen.dart
